site_name: ॐ vedic | docs
site_url: https://example.com/
theme:
   name: material
   palette:
      primary: custom
      scheme: slate

nav:
   - index.md
   - bhagavad gita: gita.md

extra_css:
   - stylesheets/extra.css

markdown_extensions:
   - admonition
   - pymdownx.details
   - pymdownx.superfences
