name: update on space
'on': push
jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Build Documentation
        run: |
          python -m pip install poetry
          python -m poetry install
          poetry run mkdocs build

      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 'latest'
      
      - name: Build UI
        run: |
          npm i yarn -g
          git clone https://github.com/externref/pinaka_frontend
          cd pinaka_frontend
          yarn install; yarn build
          cd ..

      - name: Deta Space Deployment Github Action
        uses: neobrains/space-deployment-github-action@v0.5
        with:
          access_token: '${{ secrets.ACCESS_TOKEN }}'
          project_id: '${{ secrets.PROJECT_ID }}'
          space_push: true
